// <auto-generated />
namespace ITI.UI.MVC.Auth.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addNameProp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addNameProp));
        
        string IMigrationMetadata.Id
        {
            get { return "201905051234218_addNameProp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
